Cats99/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "cats#index"
  resources :cats, except: [:index, :destroy]

end

Cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'action_view'
# require 'action_view/helpers'
# include ActionView::Helpers::DateHelper

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    CAT_COLORS = ['gray', 'ginger', 'black', 'calico', 'tabby', 'white']

    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: { in: CAT_COLORS }
    validates :sex, inclusion: { in: ["M", "F"] }
    validate :birth_date_cannot_be_in_the_future

    def birth_date_cannot_be_in_the_future
        if birth_date.present? && birth_date.to_date > Date.today
            errors.add(:birth_date)
        end
    end

    def age
        age = time_ago_in_words(birth_date)
        age.split(" ")[1..-1].join(" ")
    end

end

Cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all.order(:id)
        render :index
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def update
        @cat = Cat.find(params[:id])
        @cat.update(cat_params)
        redirect_to cat_url(@cat)
    end

    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end
end

Cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats99/app/views/cats/edit.html.erb
<h2>Edit Cat</h2>

<%= render 'cats/shared/form', cat: @cat, action: :update %>

Cats99/app/views/cats/index.html.erb
<div>
    <h2>Cats index</h2>
</div>
<!-- er, pe, pc -->
<ul>
    <% @cats.each do |cat| %>
        <li>
            <a href="<%= cat_url(cat) %>">
                <%= cat.name %>
            </a>
        </li>
    <% end %>
</ul>

Cats99/app/views/cats/new.html.erb
<h2>New Cat</h2>

<%= render 'cats/shared/form', cat: @cat, action: :create %>

Cats99/app/views/cats/shared/_form.html.erb
<% action_url = (action == :create) ? cats_url : cat_url(cat.id) %>
<% button_text  = (action == :create) ? "Create Cat" : "Update Cat"%>

<div>
    <form action="<%= action_url %>" method="POST">
        <% if action == :update %>
            <input type="hidden" name="_method" value="PATCH">
        <% end %>

        <label for="name">Name:</label>
        <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
            <br>
        <span>Sex:</span>
        <label for="m">M</label>
        <input type="radio" name="cat[sex]" id="m" value="M" <%= @cat.sex == "M" %> <%= @cat.sex == "M" ? "checked" : "" %>>
        <label for="f">F</label>
        <input type="radio" name="cat[sex]" id="f" value="F" <%= @cat.sex == "F" %> <%= @cat.sex == "F" ? "checked" : "" %>>
            <br>
        <label for="color">Color:</label>
        <select name="cat[color]" id="color">
            <option disabled selected>-- select a color --</option>
            <option value="gray" <%= @cat.color == "gray" ? "selected" : "" %> >gray</option>
            <option value="ginger" <%= @cat.color == "ginger" ? "selected" : "" %> >ginger</option>
            <option value="black" <%= @cat.color == "black" ? "selected" : "" %> >black</option>
            <option value="calico" <%= @cat.color == "calico" ? "selected" : "" %> >calico</option>
            <option value="tabby" <%= @cat.color == "tabby" ? "selected" : "" %> >tabby</option>
            <option value="white" <%= @cat.color == "white" ? "selected" : "" %> >white</option>
        </select>
            <br>
        <label for="date">Date:</label>
        <input type="date" name="cat[birth_date]" id="date" value="<%= @cat.birth_date ? @cat.birth_date : "" %>">
            <br>
        <label for="desc">Description:</label>
        <br>
        <textarea name="cat[description]" id="desc"><%= @cat.description %></textarea>
        <input type="submit" value=<%= button_text %> >
    </form>
</div>

Cats99/app/views/cats/show.html.erb
<div>
    <h2>Cat <%= @cat.id %> Show</h2>
    <h3><%= @cat.name %></h3>
    <table>
        <thead>
            <tr>
                <th>Attribute</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Age</th>
                <th><%= @cat.age %></th>
            </tr>
            <tr>
                <th>Birth_Date</th>
                <th><%= @cat.birth_date %></th>
            </tr>
            <tr>
                <th>Color</th>
                <th><%= @cat.color %></th>
            </tr>
                <th>Sex</th>
                <th><%= @cat.sex %></th>
            <tr>
            </tr>
        </tbody>
    </table>
    <div>
        <span>Description:</span><br>
        <%= @cat.description %>
    </div>
</div>

Cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>